name = "S2DExploration"
desc = "Exploring the Climatological Datasets for the Shallow-to-Deep Transition of Convection over ARM sites"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]

[deps]
ARMLive = "3cf54da3-541f-4d42-bdd0-41bf6096b485"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
ERA5Reanalysis = "99c076f5-c00e-46eb-a0bd-7ba31777c146"
ETOPO = "eb8fb1ab-fde0-4497-ad36-194d38f2cde7"
GeoRegions = "b001f823-fa75-4bff-bf55-6610c8f3688a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NASAMergedTb = "0a1892c8-8a22-4bcd-b9e2-a5b491b58d94"
NASAPrecipitation = "a018b980-0677-41c0-b9a4-7f34595c2b14"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RegionGrids = "ecebd26c-3930-4a82-94f6-9df2a191b288"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[sources]
ARMLive = {rev = "main", url = "https://github.com/natgeo-wong/ARMLive.jl.git"}
ERA5Reanalysis = {rev = "main", url = "https://github.com/GeoRegionsEcosystem/ERA5Reanalysis.jl.git"}
ETOPO = {rev = "main", url = "https://github.com/GeoRegionsEcosystem/ETOPO.jl.git"}
NASAPrecipitation = {rev = "main", url = "https://github.com/GeoRegionsEcosystem/NASAPrecipitation.jl.git"}

[compat]
julia = "1"
